export const GET_STAFFS_REQUEST = 'GET_STAFFS_REQUEST';
export const GET_STAFFS_SUCCESS = 'GET_STAFFS_SUCCESS';
export const GET_STAFFS_FAILURE = 'GET_STAFFS_FAILURE';

export const EDIT_STAFF_REQUEST = 'EDIT_STAFF_REQUEST';
export const EDIT_STAFF_SUCCESS = 'EDIT_STAFF_SUCCESS';
export const EDIT_STAFF_FAILURE = 'EDIT_STAFF_FAILURE';

export const ADD_STAFF_REQUEST = 'ADD_STAFF_REQUEST';
export const ADD_STAFF_SUCCESS = 'ADD_STAFF_SUCCESS';
export const ADD_STAFF_FAILURE = 'ADD_STAFF_FAILURE';

export const DELETE_STAFF_REQUEST = 'DELETE_STAFF_REQUEST';
export const DELETE_STAFF_SUCCESS = 'DELETE_STAFF_SUCCESS';
export const DELETE_STAFF_FAILURE = 'DELETE_STAFF_FAILURE';

export const GET_ROLES_REQUEST = 'GET_ROLES_REQUEST';
export const GET_ROLES_SUCCESS = 'GET_ROLES_SUCCESS';
export const GET_ROLES_FAILURE = 'GET_ROLES_FAILURE';

export const SET_STAFF_FORM_INITIAL_VALUES = 'SET_STAFF_FORM_INITIAL_VALUES';
