export const GET_BRANCHES_REQUEST = 'GET_BRANCHES_REQUEST';
export const GET_BRANCHES_SUCCESS = 'GET_BRANCHES_SUCCESS';
export const GET_BRANCHES_FAILURE = 'GET_BRANCHES_FAILURE';

export const GET_BRANCH_REQUEST = 'GET_BRANCH_REQUEST';
export const GET_BRANCH_SUCCESS = 'GET_BRANCH_SUCCESS';
export const GET_BRANCH_FAILURE = 'GET_BRANCH_FAILURE';

export const EDIT_BRANCH_REQUEST = 'EDIT_BRANCH_REQUEST';
export const EDIT_BRANCH_SUCCESS = 'EDIT_BRANCH_SUCCESS';
export const EDIT_BRANCH_FAILURE = 'EDIT_BRANCH_FAILURE';

export const ADD_BRANCH_REQUEST = 'ADD_BRANCH_REQUEST';
export const ADD_BRANCH_SUCCESS = 'ADD_BRANCH_SUCCESS';
export const ADD_BRANCH_FAILURE = 'ADD_BRANCH_FAILURE';

export const DELETE_BRANCH_REQUEST = 'DELETE_BRANCH_REQUEST';
export const DELETE_BRANCH_SUCCESS = 'DELETE_BRANCH_SUCCESS';
export const DELETE_BRANCH_FAILURE = 'DELETE_BRANCH_FAILURE';
