export const GET_COMPANIES_REQUEST = 'GET_COMPANIES_REQUEST';
export const GET_COMPANIES_SUCCESS = 'GET_COMPANIES_SUCCESS';
export const GET_COMPANIES_FAILURE = 'GET_COMPANIES_FAILURE';

export const GET_COMPANY_REQUEST = 'GET_COMPANY_REQUEST';
export const GET_COMPANY_SUCCESS = 'GET_COMPANY_SUCCESS';
export const GET_COMPANY_FAILURE = 'GET_COMPANY_FAILURE';

export const GET_COMPANY_BRANCHES_REQUEST = 'GET_COMPANY_BRANCHES_REQUEST';
export const GET_COMPANY_BRANCHES_SUCCESS = 'GET_COMPANY_BRANCHES_SUCCESS';
export const GET_COMPANY_BRANCHES_FAILURE = 'GET_COMPANY_BRANCHES_FAILURE';

export const EDIT_COMPANY_REQUEST = 'EDIT_COMPANY_REQUEST';
export const EDIT_COMPANY_SUCCESS = 'EDIT_COMPANY_SUCCESS';
export const EDIT_COMPANY_FAILURE = 'EDIT_COMPANY_FAILURE';

export const ADD_COMPANY_REQUEST = 'EDIT_COMPANY_REQUEST';
export const ADD_COMPANY_SUCCESS = 'EDIT_COMPANY_SUCCESS';
export const ADD_COMPANY_FAILURE = 'EDIT_COMPANY_FAILURE';

export const DELETE_COMPANY_REQUEST = 'DELETE_COMPANY_REQUEST';
export const DELETE_COMPANY_SUCCESS = 'DELETE_COMPANY_SUCCESS';
export const DELETE_COMPANY_FAILURE = 'DELETE_COMPANY_FAILURE';
