export const GET_KITCHENS_REQUEST = 'GET_KITCHENS_REQUEST';
export const GET_KITCHENS_SUCCESS = 'GET_KITCHENS_SUCCESS';
export const GET_KITCHENS_FAILURE = 'GET_KITCHENS_FAILURE';

export const GET_KITCHEN_REQUEST = 'GET_KITCHEN_REQUEST';
export const GET_KITCHEN_SUCCESS = 'GET_KITCHEN_SUCCESS';
export const GET_KITCHEN_FAILURE = 'GET_KITCHEN_FAILURE';

export const EDIT_KITCHEN_REQUEST = 'EDIT_KITCHEN_REQUEST';
export const EDIT_KITCHEN_SUCCESS = 'EDIT_KITCHEN_SUCCESS';
export const EDIT_KITCHEN_FAILURE = 'EDIT_KITCHEN_FAILURE';

export const ADD_KITCHEN_REQUEST = 'ADD_KITCHEN_REQUEST';
export const ADD_KITCHEN_SUCCESS = 'ADD_KITCHEN_SUCCESS';
export const ADD_KITCHEN_FAILURE = 'ADD_KITCHEN_FAILURE';

export const DELETE_KITCHEN_REQUEST = 'DELETE_KITCHEN_REQUEST';
export const DELETE_KITCHEN_SUCCESS = 'DELETE_KITCHEN_SUCCESS';
export const DELETE_KITCHEN_FAILURE = 'DELETE_KITCHEN_FAILURE';
