export const GET_TABLES_REQUEST = 'GET_TABLES_REQUEST';
export const GET_TABLES_SUCCESS = 'GET_TABLES_SUCCESS';
export const GET_TABLES_FAILURE = 'GET_TABLES_FAILURE';

export const GET_SECTIONS_REQUEST = 'GET_SECTIONS_REQUEST';
export const GET_SECTIONS_SUCCESS = 'GET_SECTIONS_SUCCESS';
export const GET_SECTIONS_FAILURE = 'GET_SECTIONS_FAILURE';

export const GET_TABLE_REQUEST = 'GET_TABLE_REQUEST';
export const GET_TABLE_SUCCESS = 'GET_TABLE_SUCCESS';
export const GET_TABLE_FAILURE = 'GET_TABLE_FAILURE';

export const EDIT_TABLE_REQUEST = 'EDIT_TABLE_REQUEST';
export const EDIT_TABLE_SUCCESS = 'EDIT_TABLE_SUCCESS';
export const EDIT_TABLE_FAILURE = 'EDIT_TABLE_FAILURE';

export const ADD_TABLE_REQUEST = 'ADD_TABLE_REQUEST';
export const ADD_TABLE_SUCCESS = 'ADD_TABLE_SUCCESS';
export const ADD_TABLE_FAILURE = 'ADD_TABLE_FAILURE';
export const ADD_GENERATED_TABLE_CODE = 'ADD_GENERATED_TABLE_CODE';

export const DELETE_TABLE_REQUEST = 'DELETE_KITCHEN_REQUEST';
export const DELETE_TABLE_SUCCESS = 'DELETE_KITCHEN_SUCCESS';
export const DELETE_TABLE_FAILURE = 'DELETE_KITCHEN_FAILURE';
